### DISCUSSION TITLE
Custom login flow

### DISCUSSION THREAD

**Discussion by AlithAnar** [rpivo/react-automation-profiler#63] [Ideas]
I'd like to analyze my app which is currently available only after successful login (redirect to accounts page -> login -> back to the localhost with a token). This flow is quite unique and for test purposes, I've added logging in manually in automation.ts:

```TS
  async function login() {
    await page.waitForSelector('input[name=email]');
    await page.focus('input[name=email]');
    await page.keyboard.type('john@example.com');

    await page.waitForSelector('input[name=password]');
    await page.focus('input[name=password]');
    await page.keyboard.type('*********');

    await page.waitForTimeout(1000);
    await page.keyboard.press('Enter');
  }

  await page.goto(url);
  try {
    await login();
    await page.waitForTimeout(5000);
  } catch (e) {
    console.error(e);
  }
```

How could we handle this using yaml config language? my early proposal:

```YAML
(optional) leading-steps:
   - waitfor input[name=email]
   - waitfor input[name=password]
   - focus input[name=email]
   - type john@example.com
   - focus input[name=password]
   - type *****
   - wait 1000
   - press Enter
   - wait 5000
main-steps:
   Flow 1:
      - click <selector1>
      - click <selector2>
   Flow 2:
      - click <selector3>
```

@rpivo WDYT?
